## This is a sample Machine Learning project that exemplifies how to proceed Correspondence Analysis, Simple (SCA) and Multiple (MCA), using Python, Pandas, NumPy, SciPy, Statsmodels, Prince, Matplotlib, Seaborn and Plotly, along with Anaconda managed environments

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
plt.style.use("dark_background")
import seaborn as sns
from scipy.stats import chi2_contingency
from scipy import stats
import statsmodels.api as sm
import prince
import os
import plotly.graph_objects as go
import plotly.io as pio
if os.getenv("GITHUB_ACTIONS") == "true":
    pio.renderers.default = "png"
else:
    pio.renderers.default='colab'

- the formulas shown at this notebook have been taken from the following reference:

    FÁVERO, L. P.; BELFIORE, P. Manual de Análise de Dados: Estatística e Machine Learning com Excel®, SPSS®, Stata®, R® e Python®. 2ª edição, 1288 p. Brasil: ccGEN LTC, 2024.
    
    Available in Brazil at:
    
    https://www.amazon.com.br/Manual-An-C3-A1lise-Dados-Estat-C3-ADstica-Learning-dp-8595159920/dp/8595159920

## Use Case Scenario and Data - Investments' Categories per Client Profile. And a General Overview about Correspondence Analysis.

This use case shows an example of how to use Simple Correspondence Analysis (SCA), a non-supervised Machine Learning (ML) technique, to plot into a graph the categories of qualitative variables (doesn't work for quantitative variables), namely Profile (of the investor) - line variable - and Investment (predominant type) - column variable. These variables and their categories are displayed onto a contingency table, in a matrix format, that displays the multivariate frequency distribution of the variables' categories. We do not count the variables, we count each category, or class, inside each variable, and, ultimately, plot those on the perceptual map (graph). Client Profile variable has, as possible category classes: Agressive, Conservative or Moderate. While Investiment variable has, as possible category classes: Stocks, Bonds and Savings. The quantity of possible dimensions (axes) of the graph is calculated as m = min(I – 1, J – 1), being I and J the number of categories of the line and column variables. In our case, as we have 2 variables with 3 categories each, that would give us min((3-1),(3-1)) = 2. Therefore, we have a case with two dimensions, that is, with 2 eigenvalues, each one with a certain inertia, which is similar to the variance we had with Factorial Analysis, and thus represents the quantity of data distributed throughout each axis or dimension. The first dimension (or lambda 1), i.e., the X dimension, is the one with the most inertia of data represented, followed by the second dimension (or lambda 2), i.e., the Y dimension... and if there are more dimensions, the inertia drops even further. These are the dimensions (axes X and Y) of the perceptual map onto which each category "dot" will be plotted, according to their respective coordinates. The goal of this Analysis is to calculate these coordinates and finally be able to analyse if any of the line categories relates to any of the column categories, that is, if the variables are generically related and through which categories, specifically, that relation stands. The closer the categories are plotted, the closer they relate to each other, for each line and column variable. In this case, we'll have only the 2 axes X and Y (that's why it's a Simple Correspondence Analysis, and not Multiple) and 6 categories plotted at the graph, 3 for the line variable and 3 for the column variable. We wanna check if any of these relates to each other (always comparing correpondent pairs of categories, one from the line Dimension (X) and another from the column Dimension (Y))... we do not compare categories from the same dimension or axis. If Multiple Correspondence Analysis (MCA) is used (more than 2 lambdas), then we have more than 2 dimensions or variables, which is another use case at this same notebook project. The number of categories, for each dimension, could be any. For this example, we have only two dimensions or qualitative variables, with 3 categories each. 

The SCA method follows the sequence below:
- create a contingency table (crostab) with the distribution of observed frequencies of categories of each variable
- calculate and mount another table with the expected frequencies
- calculate and mount another table with the residuals, then the standardized residuals, then the adjusted standardized residuals
- calculate the Chi square statistic (partial and total)
- calculate the p-value for the Chi square statistic, in order to check if there is a statistically significant association (dependency) between the two variables. If not, do not proceed, the correspondence analysis won't be possible. If the p-value is below .05 (5%), or any other significance alfa you decide, then the qualitative variables are statistically dependent on each other. This hypothesis test is done on the Chi square distribution. Then you may proceed to check, based on what specific categories - inside the variables, that dependency of the variables is sustained
- to check what categories depend on each other, and therefore make the variables also dependent on each other, you now compare the adjusted standardized residuals, at the respective table. This hypothesis test, in turn, is done on a Z Standard Normal Distribution. For each pair of categories (one from each variable), you have that adjusted residual, and, if it's value is above 1.96 (the critical value for the hypothesis test, with a 5% significance value, at a Z Distribution), then those two categories relate to each other and, thus, contribute to the relation or dependency between their respective variables. If the variables depend on each other, it is because at least some of their categories also depend on each other. We wanna know which are those determinant categories
- now, for actually calculating the coordinates and plot the perceptual map graph, we calculate the eigenvalues, by first calculating the Matrix A, then the Matrix W. For the Matrix W we calculate the Det(W – λ . I ) = 0 equation, and finally get the absolute lambdas, one per dimension. The sum of the lambdas (inertia) is the principal total inertia. Which can also be calculated from the total Chi square. We can also calculate the relative inertia, for each lambda or dimension (the ammount of data - variance - represented at each axis)
- calculate the Mass of variables for the line variable (3 result values) and for the column variable (other 3 result variables). With these, mount the line Mass and column Mass Matrices
- now, for each lambda, we calculate its singular value
- calculate the eigenvectors for the column variable (v) and line variable (u)
- finally, and based on the respective eigenvectors, calculate the coordinates X and Y of the column and line variables' categories, plotting these on the perceptual map graph, and analyse the distance between any near categories (always one category from a variable or dimension, and another category from another variable or dimension). The usefulness of such a graph is that we can see all categories from all dimensions, all at once, on one same graph... differently from the tables we had created so far

For MCA, see the other .ipynb at this same project repository. Most of what we saw for SCA is the same for MCA.

In [2]:
# reading and displaying our dataset
client_financial_products = pd.read_excel("client-financial-products.xlsx")
client_financial_products

         CLIENT       PROFILE INVESTMENT
0      Gabriela  Conservative    Savings
1   Luiz Felipe  Conservative    Savings
2      Patrícia  Conservative    Savings
3       Gustavo  Conservative    Savings
4       Letícia  Conservative    Savings
..          ...           ...        ...
95       Sheila    Aggressive     Stocks
96        Pedro    Aggressive     Stocks
97      Horácio    Aggressive     Stocks
98      Leandro    Aggressive     Stocks
99       Estela    Aggressive     Stocks

[100 rows x 3 columns]

In [3]:
client_financial_products["PROFILE"].value_counts()

PROFILE
Aggressive      58
Moderate        25
Conservative    17
Name: count, dtype: int64

In [4]:
client_financial_products["INVESTMENT"].value_counts()

INVESTMENT
Stocks     45
Bonds      40
Savings    15
Name: count, dtype: int64

In [5]:
# creating and showing the contingency table with the two variables (and their categories)
# The two qualitative variables are: PROFILE (line) and INVESTMENT (column). PROFILE categories are: Aggressive, Conservative and 
# Moderate. INVESTMENT categories are: Bonds, Savings and Stocks.
# This table contains the absolute observed frequencies of the observations
contingency_df = pd.crosstab(client_financial_products["PROFILE"], client_financial_products["INVESTMENT"], 
                             margins=True, margins_name="TOTAL").reindex(["Aggressive","Conservative","Moderate", "TOTAL"])[["Stocks","Bonds","Savings", "TOTAL"]]
contingency_df

INVESTMENT    Stocks  Bonds  Savings  TOTAL
PROFILE
Aggressive        36     20        2     58
Conservative       5      4        8     17
Moderate           4     16        5     25
TOTAL             45     40       15    100

In [6]:
# creating aux method to reset values at dataframe
def reset_all_df_cells_to_float_nan(df):
    df = df.astype("float64")
    df.loc[:] = np.nan
    return df

In [7]:
# calculating and showing the absolute expected frequencies of the observations
expected_freq_df = contingency_df.copy()
if("TOTAL" in expected_freq_df.columns):
    expected_freq_df.drop("TOTAL",axis=1,inplace=True)    
if("TOTAL" in expected_freq_df.index):
    expected_freq_df.drop("TOTAL",axis=0,inplace=True)
expected_freq_df = reset_all_df_cells_to_float_nan(expected_freq_df)
expected_freq_df.loc["Aggressive","Stocks"] = contingency_df.loc["TOTAL","Stocks"]*contingency_df.loc["Aggressive","TOTAL"]/contingency_df.loc["TOTAL","TOTAL"]
expected_freq_df.loc["Aggressive","Bonds"] = contingency_df.loc["TOTAL","Bonds"]*contingency_df.loc["Aggressive","TOTAL"]/contingency_df.loc["TOTAL","TOTAL"]
expected_freq_df.loc["Aggressive","Savings"] = contingency_df.loc["TOTAL","Savings"]*contingency_df.loc["Aggressive","TOTAL"]/contingency_df.loc["TOTAL","TOTAL"]
expected_freq_df.loc["Conservative","Stocks"] = contingency_df.loc["TOTAL","Stocks"]*contingency_df.loc["Conservative","TOTAL"]/contingency_df.loc["TOTAL","TOTAL"]
expected_freq_df.loc["Conservative","Bonds"] = contingency_df.loc["TOTAL","Bonds"]*contingency_df.loc["Conservative","TOTAL"]/contingency_df.loc["TOTAL","TOTAL"]
expected_freq_df.loc["Conservative","Savings"] = contingency_df.loc["TOTAL","Savings"]*contingency_df.loc["Conservative","TOTAL"]/contingency_df.loc["TOTAL","TOTAL"]
expected_freq_df.loc["Moderate","Stocks"] = contingency_df.loc["TOTAL","Stocks"]*contingency_df.loc["Moderate","TOTAL"]/contingency_df.loc["TOTAL","TOTAL"]
expected_freq_df.loc["Moderate","Bonds"] = contingency_df.loc["TOTAL","Bonds"]*contingency_df.loc["Moderate","TOTAL"]/contingency_df.loc["TOTAL","TOTAL"]
expected_freq_df.loc["Moderate","Savings"] = contingency_df.loc["TOTAL","Savings"]*contingency_df.loc["Moderate","TOTAL"]/contingency_df.loc["TOTAL","TOTAL"]
expected_freq_df

INVESTMENT    Stocks  Bonds  Savings
PROFILE
Aggressive     26.10   23.2     8.70
Conservative    7.65    6.8     2.55
Moderate       11.25   10.0     3.75

In [8]:
# calculating and showing the residuals
residuals_df = contingency_df.copy()
if("TOTAL" in residuals_df.columns):
    residuals_df.drop("TOTAL",axis=1,inplace=True)    
if("TOTAL" in residuals_df.index):
    residuals_df.drop("TOTAL",axis=0,inplace=True)
residuals_df = reset_all_df_cells_to_float_nan(residuals_df)
residuals_df.loc["Aggressive","Stocks"] = contingency_df.loc["Aggressive","Stocks"]-expected_freq_df.loc["Aggressive","Stocks"]
residuals_df.loc["Aggressive","Bonds"] = contingency_df.loc["Aggressive","Bonds"]-expected_freq_df.loc["Aggressive","Bonds"]
residuals_df.loc["Aggressive","Savings"] = contingency_df.loc["Aggressive","Savings"]-expected_freq_df.loc["Aggressive","Savings"]
residuals_df.loc["Conservative","Stocks"] = contingency_df.loc["Conservative","Stocks"]-expected_freq_df.loc["Conservative","Stocks"]
residuals_df.loc["Conservative","Bonds"] = contingency_df.loc["Conservative","Bonds"]-expected_freq_df.loc["Conservative","Bonds"]
residuals_df.loc["Conservative","Savings"] = contingency_df.loc["Conservative","Savings"]-expected_freq_df.loc["Conservative","Savings"]
residuals_df.loc["Moderate","Stocks"] = contingency_df.loc["Moderate","Stocks"]-expected_freq_df.loc["Moderate","Stocks"]
residuals_df.loc["Moderate","Bonds"] = contingency_df.loc["Moderate","Bonds"]-expected_freq_df.loc["Moderate","Bonds"]
residuals_df.loc["Moderate","Savings"] = contingency_df.loc["Moderate","Savings"]-expected_freq_df.loc["Moderate","Savings"]
residuals_df

INVESTMENT    Stocks  Bonds  Savings
PROFILE
Aggressive      9.90   -3.2    -6.70
Conservative   -2.65   -2.8     5.45
Moderate       -7.25    6.0     1.25

In [9]:
# calculating and showing manually the Chi square patials and total
chi2_df = contingency_df.copy()
if("TOTAL" in chi2_df.columns):
    chi2_df.drop("TOTAL",axis=1,inplace=True)    
if("TOTAL" in chi2_df.index):
    chi2_df.drop("TOTAL",axis=0,inplace=True)
chi2_df = reset_all_df_cells_to_float_nan(chi2_df)
chi2_df.loc["Aggressive","Stocks"] = np.square(residuals_df.loc["Aggressive","Stocks"])/expected_freq_df.loc["Aggressive","Stocks"]
chi2_df.loc["Aggressive","Bonds"] = np.square(residuals_df.loc["Aggressive","Bonds"])/expected_freq_df.loc["Aggressive","Bonds"]
chi2_df.loc["Aggressive","Savings"] = np.square(residuals_df.loc["Aggressive","Savings"])/expected_freq_df.loc["Aggressive","Savings"]
chi2_df.loc["Conservative","Stocks"] = np.square(residuals_df.loc["Conservative","Stocks"])/expected_freq_df.loc["Conservative","Stocks"]
chi2_df.loc["Conservative","Bonds"] = np.square(residuals_df.loc["Conservative","Bonds"])/expected_freq_df.loc["Conservative","Bonds"]
chi2_df.loc["Conservative","Savings"] = np.square(residuals_df.loc["Conservative","Savings"])/expected_freq_df.loc["Conservative","Savings"]
chi2_df.loc["Moderate","Stocks"] = np.square(residuals_df.loc["Moderate","Stocks"])/expected_freq_df.loc["Moderate","Stocks"]
chi2_df.loc["Moderate","Bonds"] = np.square(residuals_df.loc["Moderate","Bonds"])/expected_freq_df.loc["Moderate","Bonds"]
chi2_df.loc["Moderate","Savings"] = np.square(residuals_df.loc["Moderate","Savings"])/expected_freq_df.loc["Moderate","Savings"]
print(chi2_df)
chi2_value = chi2_df.to_numpy().sum()
print(f"\nTotal Chi square: {chi2_value}")

INVESTMENT      Stocks     Bonds    Savings
PROFILE
Aggressive    3.755172  0.441379   5.159770
Conservative  0.917974  1.152941  11.648039
Moderate      4.672222  3.600000   0.416667

Total Chi square: 31.764164976335362

In [10]:
# calculating critical value for a degrees_of_freedom of (3-1)(3-1) = 4 at Chi square distribution
critical_value = stats.chi2.ppf(1-.05, df=4)
print(f"total chi square: {chi2_value} > critical value: {round(critical_value,3)}")

total chi square: 31.764164976335362 > critical value: 9.488

In [11]:
# calculating p-value for a degrees_of_freedom of (3-1)(3-1) = 4 at Chi square distribution
p_value = round(1-stats.chi2.cdf(chi2_value, 4),6)
print(f"p_value {p_value:.6f} < significance level 0.05")

p_value 0.000002 < significance level 0.05

In [12]:
print("H0 rejected. H1 confirmed ! Both because Chi square statistic > critical value, as because p-value < alfa, there IS a NOT random association between the two qualitative variables ! Now we gotta find out which categories inside the variables are responsible for that ! This way, we may proceed with the analysis !")

H0 rejected. H1 confirmed ! Both because Chi square statistic > critical value, as because p-value < alfa, there IS a NOT random association between the two qualitative variables ! Now we gotta find out which categories inside the variables are responsible for that ! This way, we may proceed with the analysis !

In [13]:
# proceeding with the Chi square test automatically (through scipy) - redoing the same we did manually right above
# we gotta drop the TOTAL edge margins before sending the contingency table to the functions below:
if("TOTAL" in contingency_df.columns):
    contingency_df.drop("TOTAL",axis=1,inplace=True)    
if("TOTAL" in contingency_df.index):
    contingency_df.drop("TOTAL",axis=0,inplace=True)
test_qui2 = chi2_contingency(contingency_df)
print(f"Chi² statistic: {round(test_qui2[0], 2)}")
print(f"p-value: {round(test_qui2[1], 6):.6f}")
print(f"degrees of freedom: {test_qui2[2]}")

Chi² statistic: 31.76
p-value: 0.000002
degrees of freedom: 4

In [14]:
# ................... calculate residuals standardized and adjusted, for each category ............ later eigen values and vectors
# and masses and sigma and coordinates.